"use strict";
exports.__esModule = true;
var arraySum_1 = require("../src/util/arraySum");
var average_1 = require("../src/util/average");
var compare_1 = require("../src/util/compare");
var inversions_1 = require("../src/util/inversions");
var isSorted_1 = require("../src/util/isSorted");
var knuthShuffle_1 = require("../src/util/knuthShuffle");
var randSeq_1 = require("../src/util/randSeq");
var swapInArray_1 = require("../src/util/swapInArray");
var uniform_1 = require("../src/util/uniform");
var Utility;
(function (Utility) {
    Utility._arraySum = arraySum_1.arraySum;
    Utility._average = average_1.average;
    Utility._compare = compare_1.compare;
    Utility._inversions = inversions_1.inversions;
    Utility._isSorted = isSorted_1.isSorted;
    Utility._knuthShuffle = knuthShuffle_1.knuthShuffle;
    Utility._randSeq = randSeq_1.randSeq;
    Utility._swapInArray = swapInArray_1.swapInArray;
    Utility._uniform = uniform_1.uniform;
})(Utility = exports.Utility || (exports.Utility = {}));
